# Generated by Django 2.1.1 on 2018-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendinghistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
