# Generated by Django 2.1 on 2018-09-17 14:58

import MyModels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('icon', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', MyModels.models.MyUserManager()),
            ],
        ),
    ]
