# Generated by Django 2.1 on 2018-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('is_shared', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
            ],
            options={
                'db_table': 'Available funds',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=17)),
                ('icon', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
            ],
            options={
                'db_table': 'Income categories',
            },
        ),
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=17)),
                ('comment', models.TextField()),
                ('funds', models.ForeignKey(on_delete=True, to='MyModels.Funds')),
                ('income', models.ForeignKey(on_delete=True, to='MyModels.IncomeCategories')),
            ],
            options={
                'db_table': 'Income history',
            },
        ),
        migrations.CreateModel(
            name='SharedFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.ForeignKey(on_delete=True, to='MyModels.Funds')),
                ('group', models.ForeignKey(on_delete=True, to='MyModels.Group')),
            ],
            options={
                'db_table': 'Shared funds',
            },
        ),
        migrations.CreateModel(
            name='SharedSpendingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=True, to='MyModels.Group')),
            ],
            options={
                'db_table': 'Shared spending categories',
            },
        ),
        migrations.CreateModel(
            name='SpendingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('is_shared', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
            ],
            options={
                'db_table': 'Spending categories',
            },
        ),
        migrations.CreateModel(
            name='SpendingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=17)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('funds', models.ForeignKey(on_delete=True, to='MyModels.Funds')),
                ('owner', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
                ('spending_categories', models.ForeignKey(on_delete=True, to='MyModels.SpendingCategories')),
            ],
            options={
                'db_table': 'Spending history',
            },
        ),
        migrations.CreateModel(
            name='UsersInGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=True, to='MyModels.Group')),
                ('user', models.ForeignKey(on_delete=True, to='MyModels.MyUser')),
            ],
            options={
                'db_table': 'Users in groups',
            },
        ),
        migrations.AddField(
            model_name='sharedspendingcategories',
            name='spending_categories',
            field=models.ForeignKey(on_delete=True, to='MyModels.SpendingCategories'),
        ),
    ]
