# Generated by Django 2.1.1 on 2018-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingLimitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('spending_category', models.ForeignKey(on_delete=True, to='spending.SpendingCategories')),
            ],
        ),
    ]
