# Generated by Django 2.1.1 on 2018-11-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_spendinglimitationgroup_spendinglimitationindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
