# Generated by Django 2.1.1 on 2018-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_erwr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='erwr_name',
        ),
    ]
