# Generated by Django 2.1.1 on 2018-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile_one_time_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ind_period_fixed',
            field=models.BooleanField(null=True),
        ),
    ]
