# Generated by Django 2.1.1 on 2018-11-12 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=True, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
