# Generated by Django 2.1.1 on 2018-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('icon', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=True, to='authentication.UserProfile')),
            ],
        ),
    ]
