# Generated by Django 2.1.1 on 2018-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
