# Generated by Django 2.1.1 on 2018-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0001_initial'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('comment', models.TextField(default='', null=True)),
                ('fund', models.ForeignKey(on_delete=True, related_name='income_history', to='fund.FundCategories')),
                ('income', models.ForeignKey(on_delete=True, related_name='income_history', to='income.IncomeCategories')),
            ],
        ),
    ]
