# Generated by Django 2.1.1 on 2018-10-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='fund.FundCategories')),
            ],
        ),
    ]
