# Generated by Django 2.1.1 on 2018-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
